# 调试模式 debug
debug: true

# 语言 language
lang: en_US

# 物品修订器 用于实现物品更新
# Item Revision for Item updating
itemRevision: {}


# 模块
# 修改之后需要重启服务器应用更改
# Modules
# Restart is required to apply changes
modules:
  sertraline:
    feature: true
    editor: true
  xbuilder:
    feature: true
    editor: true
  minecraft:
    feature: true
    editor: false
  visual:
    feature: true
    editor: false
  mmo:
    feature: true
    editor: true
    dependency:
      - MythicLib
  eco:
    feature: true
    editor: true
    dependency:
      - libreforge

placeholders:
  plus: "+"
  minus: "-"

# 发包相关功能
packet:
  # 是否注册包处理器
  # 不启用或不安装packetevents 2.10+ 所有发包功能均不会生效
  # 修改后需要重启服务器
  register: true

  # 是否启用发包Lore
  # 修改后需要重启服务器
  packet-lore: true

  # 是否启用发包组件
  # 修改后需要重启服务器
  packet-component: true

# 标签解析
tags:
  sertraline: true
  papi: true
  val: true
  var: true
  dynamic: true

action:
  # 节流时间，防止过多执行动作，单位为ms
  throttle-time: 500