# Sertraline Configuration
# 大部分设置需要重启以应用更改
# MOST SETTINGS REQUIRED RESTART TO APPLY CHANGES
# 大部分设置需要重启以应用更改
# MOST SETTINGS REQUIRED RESTART TO APPLY CHANGES
# 大部分设置需要重启以应用更改
# MOST SETTINGS REQUIRED RESTART TO APPLY CHANGES
# 大部分设置需要重启以应用更改
# MOST SETTINGS REQUIRED RESTART TO APPLY CHANGES

# 调试模式 debug
# Debug mode
debug: false

# 语言 language
lang: en_US

# 物品修订器 用于实现物品更新 尚未实现
# Item Revision for Item updating
item-revision: {}

file-load:

  # If you want to use \ like \. , You must use \\. instead.
  item: "^(?![#!]).*\\.(?i)(yaml|yml|toml|tml|json|conf)$"
  lore-format: "^(?![#!]).*\\.(?i)(yaml|yml|toml|tml|json|conf)$"
  mapping: "^(?![#!]).*\\.(?i)(yaml|yml|toml|tml|json|conf)$"



preload:

  # 预编译脚本
  # Pre-compile scripts
  script:
    graaljs: true
    javascript: true
    jexl: true

# 模块
# Modules
modules:
  sertraline:
    feature: true
    editor: true
  xbuilder:
    feature: true
    editor: true
  minecraft:
    feature: true
    editor: false
  visual:
    feature: true
    editor: false
  mmo:
    feature: true
    editor: true
  eco:
    feature: true
    editor: true

placeholders:
  plus: "+"
  minus: "-"

rebuild:
  keep-data:
    - sertraline_data
    - sertraline_revision
# 警告: keep-component 在部分情境下不会生效，不保证该功能可以稳定运行。
# Warning: keep-component may not work in some cases, and it is not guaranteed to run stably.
# keep-component:
#   - minecraft:custom_name

# 发包相关功能
# Packet related features
packet:
  # 是否注册包处理器
  # 不启用或不安装packetevents 2.10+ 所有发包功能均不会生效
  # Whether to register the packet handler
  # If not enabled or packetevents 2.10+ is not installed, all packet sending functions will not take effect
  register: true

  # 是否启用发包Lore
  # Whether to enable packet Lore
  packet-lore: true

  # 是否启用发包组件
  # Whether to enable packet component
  packet-component: true

# 标签解析
# Tag parsing
tags:
  sertraline: true
  papi: true
  val: true
  var: true
  dynamic: true

action:

  # 默认节流时间
  # Default throttle time
  throttle-time: 500

  # 为每个动作设置不同的节流时间
  # 0 = 禁用节流
  # Set different throttling times for each action
  # 0 to disable
  throttle:
    onConsume: 0
